using System;
using Urc.Protocol;

namespace Urc.Editor
{
    internal enum UrcJobState
    {
        Queued,
        Running,
        Done,
        /// <summary>Died with the domain. Only reachable for work that yields the main thread.</summary>
        Interrupted,
    }

    /// <summary>
    /// One unit of work, and everything needed to answer for it after a domain reload.
    ///
    /// Jobs are journalled to <see cref="UrcJobStore"/> at state transitions. That journal — not the
    /// socket — is the source of truth, which is what lets a client reconnect after a reload and
    /// still get its answer.
    /// </summary>
    internal sealed class UrcJob
    {
        /// <summary>Generated by the client, which is what makes `attach` idempotent.</summary>
        public string Id;

        public string Cmd;
        public UrcJobState State = UrcJobState.Queued;

        /// <summary>One of <see cref="UrcProtocol.Status"/>, once terminal.</summary>
        public string Status;
        public string Summary;

        /// <summary>Bounded projection of the return value. Never unbounded — this lives in SessionState.</summary>
        public Json Value;

        /// <summary>Domain generation when the job started, and when it finished. Differ across a reload.</summary>
        public int StartedGeneration;
        public int FinishedGeneration;

        public string StartedAtUtc;
        public string FinishedAtUtc;

        /// <summary>Pid of the client that submitted it — used to reclaim the connection slot if it dies.</summary>
        public int ClientPid;

        /// <summary>
        /// Counts of what the editor logged during this job, plus the cursor to fetch it.
        /// Deliberately counts and a pointer, never the text: results persist in an agent's context
        /// for the whole session, so the caller decides whether the output is worth reading.
        /// </summary>
        public Json Logs;

        /// <summary>Path to the full value when it was too large to inline.</summary>
        public string ValueArtifact;

        /// <summary>
        /// What was asked for, in human terms — the snippet source for an exec. Shown in the editor
        /// window's history so a person can see what an agent actually ran. Not journalled: it is
        /// only meaningful live, and snippets can be large.
        /// </summary>
        [NonSerialized] public string Detail;

        /// <summary>
        /// How <see cref="Detail"/> was assembled, when the client combined several sources:
        /// `[{name, line, lines}]`. Absent for a single source, where there is nothing to split.
        /// </summary>
        [NonSerialized] public Json Sources;

        public bool IsTerminal => State == UrcJobState.Done || State == UrcJobState.Interrupted;

        public static UrcJob Create(string id, string cmd, int clientPid) => new UrcJob
        {
            Id = id,
            Cmd = cmd,
            ClientPid = clientPid,
            State = UrcJobState.Queued,
            StartedGeneration = UrcEditorState.Generation,
            StartedAtUtc = DateTime.UtcNow.ToString("o"),
        };

        public void Complete(string status, string summary, Json value)
        {
            Status = status;
            Summary = summary;
            Value = value;
            State = status == UrcProtocol.Status.Interrupted ? UrcJobState.Interrupted : UrcJobState.Done;
            FinishedGeneration = UrcEditorState.Generation;
            FinishedAtUtc = DateTime.UtcNow.ToString("o");
        }

        public Json ToJson() =>
            Json.Object()
                .Set("id", Id)
                .Set("cmd", Cmd)
                .Set("state", State.ToString().ToLowerInvariant())
                .SetIf("status", Status)
                .SetIf("summary", Summary)
                .SetIf("value", Value)
                .Set("startedGeneration", StartedGeneration)
                .Set("finishedGeneration", FinishedGeneration)
                .SetIf("startedAt", StartedAtUtc)
                .SetIf("finishedAt", FinishedAtUtc)
                .Set("clientPid", ClientPid);

        public static UrcJob FromJson(Json json)
        {
            var id = json["id"].AsString();
            if (string.IsNullOrEmpty(id)) return null;

            return new UrcJob
            {
                Id = id,
                Cmd = json["cmd"].AsString(""),
                State = ParseState(json["state"].AsString()),
                Status = json["status"].AsString(),
                Summary = json["summary"].AsString(),
                Value = json["value"],
                StartedGeneration = json["startedGeneration"].AsInt(),
                FinishedGeneration = json["finishedGeneration"].AsInt(),
                StartedAtUtc = json["startedAt"].AsString(),
                FinishedAtUtc = json["finishedAt"].AsString(),
                ClientPid = json["clientPid"].AsInt(),
            };
        }

        private static UrcJobState ParseState(string value)
        {
            switch (value)
            {
                case "queued": return UrcJobState.Queued;
                case "running": return UrcJobState.Running;
                case "done": return UrcJobState.Done;
                case "interrupted": return UrcJobState.Interrupted;
                default: return UrcJobState.Queued;
            }
        }

        /// <summary>The `result` frame a client receives, whether live or via `attach` after a reload.</summary>
        public Json ToResultFrame() =>
            Json.Object()
                .Set("ev", UrcProtocol.Ev.Result)
                .Set("jobId", Id)
                .Set("status", Status ?? UrcProtocol.Status.Interrupted)
                .SetIf("summary", Summary)
                .SetIf("value", Value)
                .SetIf("valueArtifact", ValueArtifact)
                .SetIf("logs", Logs)
                .Set("generation", FinishedGeneration != 0 ? FinishedGeneration : StartedGeneration);
    }
}
